"use client";

import axios from "axios";
import { useRouter } from "next/navigation";
import { useState } from "react";
import toast from "react-hot-toast";

export default function TwoFactorSetup() {
  const router = useRouter();

  const [password, setPassword] = useState("");
  const [otp, setOtp] = useState("");

  const [qrImg, setQrImg] = useState("");
  const [otpSecret, setOtpSecret] = useState("");

  const [isSettingUp, setIsSettingUp] = useState(false);
  const [isVerifying, setIsVerifying] = useState(false);

  const startSetup = async (e: React.SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault();

    if (!password) {
      toast.error("Please enter your password");
      return;
    }

    try {
      setIsSettingUp(true);

      const response = await axios.post("/api/auth/2fa/setup", {
        password,
      });

      setQrImg(response.data.qrCode);
      setOtpSecret(response.data.secret);

      toast.success("Password verified. Scan the QR code.");
    } catch (error: any) {
      toast.error(
        error.response?.data?.message ||
          "Unable to start 2FA setup"
      );
    } finally {
      setIsSettingUp(false);
    }
  };

  const verifySetup = async (
    e: React.SyntheticEvent<HTMLFormElement>
  ) => {
    e.preventDefault();

    if (!otp) {
      toast.error("Please enter the OTP");
      return;
    }

    if (otp.length !== 6) {
      toast.error("OTP must be 6 digits");
      return;
    }

    try {
      setIsVerifying(true);

      const response = await axios.post(
        "/api/auth/2fa/verify-setup",
        {
          otpSecret,
          otp,
        }
      );

      toast.success(response.data.message);

      router.push("/profile");
    } catch (error: any) {
      toast.error(
        error.response?.data?.message ||
          "2FA verification failed"
      );
    } finally {
      setIsVerifying(false);
    }
  };

  return (
    <main className="min-h-screen bg-[#111111] text-white flex items-center justify-center px-4">
      <div className="w-full max-w-md rounded-2xl border border-zinc-800 bg-[#181818] p-8">

        <h1 className="text-2xl font-bold text-center">
          Enable Two-Factor Authentication
        </h1>

        {!qrImg ? (
          <>
            <p className="mt-3 text-center text-sm text-zinc-400">
              Enter your current password to start setting up
              two-factor authentication.
            </p>

            <form onSubmit={startSetup} className="mt-8">
              <label
                htmlFor="password"
                className="block text-sm text-zinc-300 mb-2"
              >
                Password
              </label>

              <input
                type="password"
                id="password"
                name="password"
                value={password}
                placeholder="Enter your password"
                onChange={(e) => setPassword(e.target.value)}
                className="w-full px-4 py-3 rounded-lg bg-zinc-900 border border-zinc-800 text-white outline-none focus:border-white"
              />

              <button
                type="submit"
                disabled={isSettingUp}
                className="mt-5 w-full rounded-lg bg-blue-500 px-4 py-3 font-semibold transition hover:bg-blue-600 disabled:cursor-not-allowed disabled:opacity-50"
              >
                {isSettingUp
                  ? "Verifying password..."
                  : "Continue"}
              </button>
            </form>
          </>
        ) : (
          <>
            <p className="mt-3 text-center text-sm text-zinc-400">
              Scan this QR code using Google Authenticator or
              another authenticator app.
            </p>

            <div className="mt-6 flex justify-center rounded-xl bg-white p-5">
              <img
                src={qrImg}
                alt="2FA QR Code"
                className="h-56 w-56"
              />
            </div>

            <p className="mt-5 text-center text-sm text-zinc-400">
              After scanning the QR code, enter the 6-digit code
              generated by your authenticator app.
            </p>

            <form onSubmit={verifySetup} className="mt-6">
              <label
                htmlFor="otp"
                className="block text-sm text-zinc-300 mb-2"
              >
                Authentication Code
              </label>

              <input
                type="text"
                id="otp"
                name="otp"
                value={otp}
                maxLength={6}
                inputMode="numeric"
                placeholder="Enter 6-digit code"
                onChange={(e) =>
                  setOtp(e.target.value.replace(/\D/g, ""))
                }
                className="w-full px-4 py-3 rounded-lg bg-zinc-900 border border-zinc-800 text-white outline-none focus:border-white tracking-widest text-center"
              />

              <button
                type="submit"
                disabled={isVerifying}
                className="mt-5 w-full rounded-lg bg-green-500 px-4 py-3 font-semibold transition hover:bg-green-600 disabled:cursor-not-allowed disabled:opacity-50"
              >
                {isVerifying
                  ? "Verifying..."
                  : "Verify & Enable 2FA"}
              </button>
            </form>
          </>
        )}

        <button
          type="button"
          onClick={() => router.push("/profile")}
          className="mt-4 w-full rounded-lg border border-zinc-700 px-4 py-3 text-sm font-semibold text-zinc-300 transition hover:bg-zinc-800"
        >
          Cancel
        </button>
      </div>
    </main>
  );
}