
import { Montserrat } from "next/font/google";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


import "./globals.css";
import { Toaster } from "react-hot-toast";


const montserrat =Montserrat({
  subsets:["latin"]
})


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      
<body className={`${montserrat.className} min-h-full flex flex-col`}>
  {children}
         <Toaster
  position="top-right"
  containerStyle={{
    top: 20,
    right: 20,
  }}
  toastOptions={{
    duration: 5000,
    style: {
      maxWidth: "420px",
      whiteSpace: "normal",
      lineHeight: "1.4",
    },
  }}
/>

</body>
    </html>
  );
}
