
import type { Metadata } from "next";


import "./globals.css";
import { Toaster } from "react-hot-toast";





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
<html lang="en" className="h-full antialiased">
  <body className="min-h-full flex flex-col">
  {children}
         <Toaster
  position="top-right"
  containerStyle={{
    top: 20,
    right: 20,
  }}
  toastOptions={{
    duration: 5000,
    style: {
      maxWidth: "420px",
      whiteSpace: "normal",
      lineHeight: "1.4",
    },
  }}
/>

</body>
    </html>
  );
}
